CREATE TABLE IF NOT EXISTS USUARIO_CATEGORIA (
  ID INTEGER PRIMARY KEY,
  NOME VARCHAR(25),
  PERMISSOES JSON,
  DATA_INCLUSAO TIMESTAMP DEFAULT NOW(),
  USUARIO_INCLUSAO VARCHAR(255),
  DATA_ALTERACAO TIMESTAMP,
  USUARIO_ALTERACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USUARIO (
  ID INTEGER PRIMARY KEY,
  NOME VARCHAR(100),
  EMAIL VARCHAR(255) UNIQUE,
  LOGIN VARCHAR(25) UNIQUE,
  SENHA VARCHAR(255),
  ATIVO BOOLEAN,
  CATEGORIA_ID INTEGER CONSTRAINT FK_USUARIO_CATEGORIA REFERENCES USUARIO_CATEGORIA(ID),
  DATA_INCLUSAO TIMESTAMP DEFAULT NOW(),
  USUARIO_INCLUSAO VARCHAR(255),
  DATA_ALTERACAO TIMESTAMP,
  USUARIO_ALTERACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TURMA (
  ID INTEGER PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DATA_INCLUSAO DATE,
  DATA_ALTERACAO DATE,
  USUARIO_INCLUSAO VARCHAR(100),
  USUARIO_ALTERACAO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS USUARIO_TURMA (
  ID INTEGER PRIMARY KEY,
  USUARIO_ID INTEGER NOT NULL,
  TURMA_ID INTEGER NOT NULL,
  DATA_INCLUSAO DATE,
  DATA_ALTERACAO DATE,
  USUARIO_INCLUSAO VARCHAR(100),
  USUARIO_ALTERACAO VARCHAR(100),
  CONSTRAINT fk_usuario_turma_usuario FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
  CONSTRAINT fk_usuario_turma_turma FOREIGN KEY (TURMA_ID) REFERENCES TURMA(ID)
);

CREATE TABLE IF NOT EXISTS AVALIACAO (
  ID INTEGER PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  TIPO SMALLINT,
  DATA_INCLUSAO DATE,
  DATA_ALTERACAO DATE,
  USUARIO_INCLUSAO VARCHAR(100),
  USUARIO_ALTERACAO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PERGUNTA (
  ID INTEGER PRIMARY KEY,
  AVALIACAO_ID INTEGER NOT NULL,
  DESCRICAO TEXT,
  PESO SMALLINT,
  DATA_INCLUSAO DATE,
  DATA_ALTERACAO DATE,
  USUARIO_INCLUSAO VARCHAR(100),
  USUARIO_ALTERACAO VARCHAR(100),
  CONSTRAINT fk_pergunta_avaliacao FOREIGN KEY (AVALIACAO_ID) REFERENCES AVALIACAO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTA_ITEM (
  ID INTEGER PRIMARY KEY,
  PERGUNTA_ID INTEGER NOT NULL,
  DESCRICAO TEXT,
  DATA_INCLUSAO DATE,
  DATA_ALTERACAO DATE,
  USUARIO_INCLUSAO VARCHAR(100),
  USUARIO_ALTERACAO VARCHAR(100),
  CONSTRAINT fk_item_pergunta FOREIGN KEY (PERGUNTA_ID) REFERENCES PERGUNTA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AVALIACAO_ALUNO (
  ID INTEGER PRIMARY KEY,
  USUARIO_ID INTEGER NOT NULL,
  AVALIACAO_ID INTEGER NOT NULL,
  DATA_LIMITE DATE,
  DATA_INICIO DATE,
  DATA_FIM DATE,
  SITUACAO SMALLINT, 
  NOTA SMALLINT,
  DATA_INCLUSAO DATE,
  DATA_ALTERACAO DATE,
  USUARIO_INCLUSAO VARCHAR(100),
  USUARIO_ALTERACAO VARCHAR(100),
  CONSTRAINT fk_av_aluno_usuario FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
  CONSTRAINT fk_av_aluno_avaliacao FOREIGN KEY (AVALIACAO_ID) REFERENCES AVALIACAO(ID)
);

CREATE SEQUENCE USUARIO_CATEGORIA_SEQ_ID;
CREATE SEQUENCE USUARIO_SEQ_ID;
CREATE SEQUENCE TURMA_SEQ_ID;
CREATE SEQUENCE USUARIO_TURMA_SEQ_ID;
CREATE SEQUENCE AVALIACAO_SEQ_ID;
CREATE SEQUENCE PERGUNTA_SEQ_ID;
CREATE SEQUENCE PERGUNTA_ITEM_SEQ_ID;
CREATE SEQUENCE AVALIACAO_ALUNO_SEQ_ID;

INSERT INTO USUARIO_CATEGORIA(ID, NOME, PERMISSOES, USUARIO_INCLUSAO, DATA_INCLUSAO) VALUES (NEXTVAL('USUARIO_CATEGORIA_SEQ_ID'), 'Aluno', '["buscar_postagem"]', 'Sistema',NOW());
INSERT INTO USUARIO_CATEGORIA(ID, NOME, PERMISSOES, USUARIO_INCLUSAO, DATA_INCLUSAO) VALUES (NEXTVAL('USUARIO_CATEGORIA_SEQ_ID'), 'Professor', '["buscar_postagem","cadastrar_postagem","editar_postagem","remover_postagem","buscar_usuario","cadastrar_usuario","editar_usuario","remover_usuario","buscar_categoria",
  "cadastrar_categoria","editar_categoria","remover_categoria"]','Sistema', NOW());
INSERT INTO USUARIO_CATEGORIA(ID, NOME, PERMISSOES, USUARIO_INCLUSAO, DATA_INCLUSAO) VALUES (NEXTVAL('USUARIO_CATEGORIA_SEQ_ID'), 'Administrador', '["buscar_postagem","cadastrar_postagem","editar_postagem","remover_postagem","buscar_usuario","cadastrar_usuario","editar_usuario","remover_usuario","buscar_categoria",
  "cadastrar_categoria","editar_categoria","remover_categoria"]','Sistema', NOW());

INSERT INTO USUARIO
(ID, NOME, EMAIL, LOGIN, SENHA, ATIVO, CATEGORIA_ID, DATA_INCLUSAO, USUARIO_INCLUSAO, DATA_ALTERACAO, USUARIO_ALTERACAO)
VALUES
    (NEXTVAL('USUARIO_SEQ_ID'), 'Sistema', 'teste.exemplo@gmail.com', 'Sistema', '$2b$10$5dCdyTCFhnOAQxq2AGryF.JMwhf9bBRfzFvd7Da.J6iB22vJezXzq', true, 3, now(), 'Sistema', NULL, NULL);

SET TIME ZONE 'America/Sao_Paulo';

